Fail frontend build if the build command fails

diff --git a/frontend/Dockerfile b/frontend/Dockerfile
--- a/frontend/Dockerfile
+++ b/frontend/Dockerfile
@@ -11,6 +11,7 @@ COPY spa-build-config.json .
 ARG CACHE_BUST
 RUN npx --legacy-peer-deps openmrs@${APP_SHELL_VERSION:-next} assemble --manifest --mode config --config spa-build-config.json --target ./spa
 RUN npx --legacy-peer-deps openmrs@${APP_SHELL_VERSION:-next} build --build-config spa-build-config.json --target ./spa
+RUN [ ! -f "./spa/index.html" ] && echo "Build failed. Please check the logs above for details. This may have happened because of an update to a library that OpenMRS depends on." && exit 1
 
 FROM nginx:1.23-alpine
 
