mejora la verificación de certificados SSL en los flujos de trabajo E2E al corregir las rutas de acceso a los certificados

diff --git a/.github/workflows/e2e-tests-on-commit.yml b/.github/workflows/e2e-tests-on-commit.yml
--- a/.github/workflows/e2e-tests-on-commit.yml
+++ b/.github/workflows/e2e-tests-on-commit.yml
@@ -17,10 +17,9 @@ jobs:
 
       - name: Verify SSL Certificates
         run: |
-          ls
-          ls -l ssl/
-          test -f ssl/sihsalus-certificate.crt || { echo "Error: sihsalus-certificate.crt not found"; exit 1; }
-          test -f ssl/sihsalus-certificate.key || { echo "Error: sihsalus-certificate.key not found"; exit 1; }
+          ls -l gateway/ssl/
+          test -f gateway/ssl/sihsalus-certificate.crt || { echo "Error: sihsalus-certificate.crt not found"; exit 1; }
+          test -f gateway/ssl/sihsalus-certificate.key || { echo "Error: sihsalus-certificate.key not found"; exit 1; }
 
       - name: Build and Run Containers for E2E Tests
         run: docker compose -f e2e_test_support_files/docker-compose-build.yml up -d
